# /* ---- 💫 Cyberpunk / Darcula Hypridle ---- */  #

$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# -------------------- IDLE WARNINGS --------------------
listener {
    timeout = 540                   # 9 minutes
    on-timeout = notify-send -i $iDIR "You are idle!"
    on-resume = notify-send -i $iDIR "Oh! you're Back" "Hello!!!"
}

# -------------------- SCREEN LOCK --------------------
listener {
    timeout = 600                     # 10 minutes
    on-timeout = loginctl lock-session
}

# -------------------- SCREEN OFF --------------------
listener {
    timeout = 630                     # 10.5 minutes
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# -------------------- SUSPEND --------------------
listener {
    timeout = 1200                    # 20 minutes
    on-timeout = systemctl suspend
}
